/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_api_v1_posts_get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_api_v1_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_api_v1_posts__post_id__get"];
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_v1_posts__post_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spots */
        get: operations["list_spots_api_v1_spots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spots/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spot */
        get: operations["get_spot_api_v1_spots__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Themes */
        get: operations["list_themes_api_v1_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Theme */
        get: operations["get_theme_api_v1_themes__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/festivals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Festivals */
        get: operations["list_festivals_api_v1_festivals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/festivals/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Festival */
        get: operations["get_festival_api_v1_festivals__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Notifications */
        patch: operations["update_notifications_api_v1_auth_me_notifications_patch"];
        trace?: never;
    };
    "/api/v1/ai/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description 히스토리는 로그인한 사용자의 것만 있다.
         */
        get: operations["list_courses_api_v1_ai_courses_get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_api_v1_ai_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_v1_ai_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CourseDayRead */
        CourseDayRead: {
            /** Day */
            day: number;
            /** Title */
            title: string;
            /** Items */
            items: components["schemas"]["CourseItemRead"][];
        };
        /**
         * CourseItemRead
         * @description 응답용. 화면이 바로 쓸 수 있게 장소 정보를 붙인다.
         */
        CourseItemRead: {
            /**
             * Spot Slug
             * @description 반드시 주어진 관광지 목록의 slug 중 하나
             */
            spot_slug: string;
            /**
             * Title
             * @description 이 칸의 제목. 장소 이름과 달라도 된다
             */
            title: string;
            /**
             * Time Label
             * @description 오전 9:00 처럼 사람이 읽는 시각
             */
            time_label: string;
            /**
             * Duration Label
             * @description 80분 처럼 사람이 읽는 소요 시간
             */
            duration_label: string;
            /**
             * Reason
             * @description 왜 이 순서에 이 장소인지 한 문장
             */
            reason: string;
            /** Spot Name */
            spot_name: string;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
        };
        /** CourseRead */
        CourseRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Duration */
            duration: string;
            /** Days */
            days: components["schemas"]["CourseDayRead"][];
            /** Generated By */
            generated_by: string;
        };
        /** CourseRequest */
        CourseRequest: {
            /** Interests */
            interests?: string[];
            /**
             * Duration
             * @default 1박2일
             */
            duration: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
        };
        /** FestivalDetailRead */
        FestivalDetailRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Tagline */
            tagline: string;
            /** When Label */
            when_label: string;
            /** Badge */
            badge: string | null;
            /** Is Now */
            is_now: boolean;
            zone: components["schemas"]["Zone"];
            /** Zone Label */
            zone_label: string | null;
            /** Place */
            place: string;
            /** About */
            about: string;
            /** Hours */
            hours: string | null;
            /** Price */
            price: string | null;
            /** Tip */
            tip: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
        };
        /**
         * FestivalRead
         * @description 목록용. 홈 축제 섹션과 안내 06이 쓴다.
         */
        FestivalRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Tagline */
            tagline: string;
            /** When Label */
            when_label: string;
            /** Badge */
            badge: string | null;
            /** Is Now */
            is_now: boolean;
            zone: components["schemas"]["Zone"];
            /** Zone Label */
            zone_label: string | null;
            /** Place */
            place: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HomeRail
         * @description 홈 화면의 가로 레일 소속. 어디에도 안 실리면 NULL이다.
         * @enum {string}
         */
        HomeRail: "beach" | "food" | "hot" | "night";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MenuItem */
        MenuItem: {
            /** Name */
            name: string;
            /** Price */
            price: string;
        };
        /** NotificationSettings */
        NotificationSettings: {
            /** Weather */
            weather: boolean;
            /** Festival */
            festival: boolean;
            /** Course */
            course: boolean;
            /** Emergency */
            emergency: boolean;
            /** Marketing */
            marketing: boolean;
        };
        /** NotificationUpdate */
        NotificationUpdate: {
            /** Weather */
            weather: boolean;
            /** Festival */
            festival: boolean;
            /** Course */
            course: boolean;
            /** Emergency */
            emergency: boolean;
            /** Marketing */
            marketing: boolean;
        };
        /** PostCreate */
        PostCreate: {
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** PostRead */
        PostRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Nickname */
            nickname: string;
            /** Phone */
            phone?: string | null;
            /** Home Region */
            home_region?: string | null;
            /** Travel Style */
            travel_style?: string | null;
        };
        /** ReviewRead */
        ReviewRead: {
            /** Id */
            id: number;
            /** Author Name */
            author_name: string;
            /** Country */
            country: string;
            /** Rating */
            rating: number;
            /** Body */
            body: string;
            /** Spot Label */
            spot_label: string;
            /** Helpful Count */
            helpful_count: number;
        };
        /**
         * ReviewSummary
         * @description 홈 카루셀이 쓰는 요약. 평균과 건수를 매번 계산하지 않도록 함께 준다.
         */
        ReviewSummary: {
            /** Count */
            count: number;
            /** Average */
            average: number;
            /** Items */
            items: components["schemas"]["ReviewRead"][];
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Nickname */
            nickname: string;
            /** Phone */
            phone?: string | null;
            /** Home Region */
            home_region?: string | null;
            /** Travel Style */
            travel_style?: string | null;
            /**
             * Noti Marketing
             * @default false
             */
            noti_marketing: boolean;
        };
        /**
         * SpotCategory
         * @description 필터 칩의 택소노미. TourAPI contentTypeId와 1:1이 아니다.
         * @enum {string}
         */
        SpotCategory: "nature" | "cafe" | "history" | "food" | "downtown";
        /**
         * SpotDetailRead
         * @description 상세용. 편집 필드와 TourAPI 사실 정보를 함께 내려준다.
         */
        SpotDetailRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            zone: components["schemas"]["Zone"];
            category: components["schemas"]["SpotCategory"];
            span: components["schemas"]["SpotSpan"];
            rail: components["schemas"]["HomeRail"] | null;
            /** Sticker */
            sticker: string | null;
            /** Editorial Desc */
            editorial_desc: string;
            /** Tags */
            tags: string[];
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Image Url */
            image_url: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** About */
            about: string | null;
            /** Hours */
            hours: string | null;
            /** Tip */
            tip: string | null;
            /** Parking */
            parking: string | null;
            /** Menu */
            menu: components["schemas"]["MenuItem"][];
            /** Address */
            address: string | null;
            /** Tel */
            tel: string | null;
            /** Homepage */
            homepage: string | null;
            /** Overview */
            overview: string | null;
            /** Tour Content Id */
            tour_content_id: string | null;
        };
        /**
         * SpotRead
         * @description 목록용. 레일 카드와 권역 목록이 그리는 데 필요한 만큼만 담는다.
         */
        SpotRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            zone: components["schemas"]["Zone"];
            category: components["schemas"]["SpotCategory"];
            span: components["schemas"]["SpotSpan"];
            rail: components["schemas"]["HomeRail"] | null;
            /** Sticker */
            sticker: string | null;
            /** Editorial Desc */
            editorial_desc: string;
            /** Tags */
            tags: string[];
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Image Url */
            image_url: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
        };
        /**
         * SpotSpan
         * @description 카드가 그리드에서 차지하는 폭. 편집자가 정하는 레이아웃 지시다.
         * @enum {string}
         */
        SpotSpan: "std" | "wide" | "tall";
        /**
         * ThemeDetailRead
         * @description 상세용. 본문과 장소 목록을 덧붙인다.
         */
        ThemeDetailRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Name En */
            name_en: string;
            /** Tagline */
            tagline: string;
            /** Season */
            season: string;
            /** Car Note */
            car_note: string;
            /** Body */
            body: string;
            /** Entries */
            entries: components["schemas"]["ThemeEntryRead"][];
        };
        /**
         * ThemeEntryRead
         * @description 테마 안의 장소 한 곳.
         *
         *     note/hint는 장소의 속성이 아니라 이 테마 맥락에서의 서술이다. 그래서
         *     SpotRead 안이 아니라 밖에 둔다.
         */
        ThemeEntryRead: {
            /** Note */
            note: string;
            /** Hint */
            hint: string | null;
            spot: components["schemas"]["SpotRead"];
        };
        /**
         * ThemeRead
         * @description 목록용. 테마 카드가 그리는 데 필요한 만큼만 담는다.
         */
        ThemeRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Name En */
            name_en: string;
            /** Tagline */
            tagline: string;
            /** Season */
            season: string;
            /** Car Note */
            car_note: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Nickname */
            nickname: string;
            /** Phone */
            phone: string | null;
            /** Home Region */
            home_region: string | null;
            /** Travel Style */
            travel_style: string | null;
            notifications: components["schemas"]["NotificationSettings"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Zone
         * @description 강릉 권역. TourAPI의 sigungu는 강릉시 하나로 끝나므로 우리가 나눈 분류다.
         * @enum {string}
         */
        Zone: "gyeongpo" | "city" | "daegwallyeong" | "jumunjin" | "jeongdongjin";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_posts_api_v1_posts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"][];
                };
            };
        };
    };
    create_post_api_v1_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_v1_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_v1_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spots_api_v1_spots_get: {
        parameters: {
            query?: {
                /** @description 홈 레일 소속 */
                rail?: components["schemas"]["HomeRail"] | null;
                /** @description 권역 */
                zone?: components["schemas"]["Zone"] | null;
                /** @description 카테고리 */
                category?: components["schemas"]["SpotCategory"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spot_api_v1_spots__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_themes_api_v1_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeRead"][];
                };
            };
        };
    };
    get_theme_api_v1_themes__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_festivals_api_v1_festivals_get: {
        parameters: {
            query?: {
                /** @description 권역 */
                zone?: components["schemas"]["Zone"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FestivalRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_festival_api_v1_festivals__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FestivalDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ongangreung_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ongangreung_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ongangreung_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_notifications_api_v1_auth_me_notifications_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ongangreung_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_v1_ai_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ongangreung_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_course_api_v1_ai_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ongangreung_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_v1_ai_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_v1_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
